version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/OpenAyame/ayame
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            go fmt ./...
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/OpenAyame/ayame
    steps:
      - checkout
      - run:
          name: run build
          command: |
            go build -v
  deploy:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/OpenAyame/ayame
    steps:
      - checkout
      - run:
          name: install gox and ghr and semantics
          command: |
            go get -u github.com/mitchellh/gox
            go get -u github.com/tcnksm/ghr
            go get -u github.com/stevenmatthewt/semantics
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows" -arch="amd64" -output="dist/ayame_{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys
      - run:
          name: create release
          command: |
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
            else
            echo "The commit message(s) did not indicate a major/minor/patch version."
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
