name: Release Build
on:
  push:
    branches:
      - master         # Push events on master branch
      - 'releases/*'   # Push events to branches matching refs/heads/releases/*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: go build -v .
    - name: install gox and ghr and semantics
      run: |
        go get -u github.com/mitchellh/gox
        go get -u github.com/tcnksm/ghr
        go get -u github.com/stevenmatthewt/semantics
    - name: cross compile
      run: |
         gox -os="linux darwin windows" -arch="amd64" -output="dist/ayame_{{.OS}}_{{.Arch}}"
         cd dist/ && gzip *
    - name: create release
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         REPONAME: ${{ github.repository }}
         USERNAME: ${{ github.actor }}
         TAGNAME: ${{ github.ref }}
      run: ghr -t $GITHUB_TOKEN -u $USERNAME -r $REPONAME --replace $TAGNAME dist/
